LOGIN_PAGE = "https://www.phptravels.net/login"
EXECUTABLE_PATH = r"../../driver/geckodriver.exe"
CORRECT_LOGIN_BTN = "Login"
CORRECT_SIGNUP_BTN = "Signup"
CORRECT_EMAIL_TEXT = "Email"
CORRECT_PWD_TEXT = "Password"
CORRECT_RESET_TEXT = "Reset Password"